version: '3'
services:
  client:
    container_name: client
    build:
      context: ./client
    ports:
      - 3000:3000
    environment:
      - PORT=3000

  server:
    container_name: server
    build:
      context: ./server
    ports:
      - 4000:4000
    environment:
      - PORT=4000
      - MONGODB_URL=Đợi dũng
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - client