version: '3'
services:
  client:
    container_name: client
    build:
      context: ./client
    ports:
      - 3000:3000
    networks:
      internal_network:
        ipv4_address: 172.10.0.2

  server:
    container_name: server
    build:
      context: ./server
    ports:
      - 4000:4000
    networks:
      internal_network:
        ipv4_address: 172.10.0.3

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - client
    environment:
      - CLIENT_HOST=172.10.0.2
      - CLIENT_PORT=3000
    networks:
      internal_network:
        ipv4_address: 172.10.0.4

networks:
  internal_network:
    ipam:
      driver: default
      config:
        - subnet: 172.10.0.0/24
